# aerc.conf — sensible defaults. Editor is nvim; HTML mail rendered readable.
[general]
unsafe-accounts-conf = false

[ui]
index-columns       = date<20,name<17,flags>4,subject<*
timestamp-format    = 2006-01-02 15:04
this-day-time-format= 15:04
threading-enabled   = true
sort                = -r date
mouse-enabled       = true
fuzzy-complete      = true
border-char-vertical= │

[viewer]
pager               = less -R
alternatives        = text/plain,text/html

[filters]
text/plain    = colorize
text/html     = html | colorize
text/calendar = calendar
image/*       = catimg -w $(tput cols) -

[compose]
editor            = nvim
address-book-cmd  =

[hooks]
